project_id = "hgpjllatmfovmcnrbrtq"

[functions.google-vision-verify]
verify_jwt = false
[functions.ipma-alerts]
enabled = true
verify_jwt = true
import_map = "./functions/ipma-alerts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ipma-alerts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ipma-alerts/*.html" ]
